#!/bin/bash

echo "GitHub CLI Installation Script"
echo "=============================="
echo ""
echo "This script will help you install GitHub CLI on macOS."
echo ""
echo "Option 1: Install via Homebrew (recommended)"
echo "---------------------------------------------"
echo "If you have Homebrew installed, run:"
echo "  brew install gh"
echo ""
echo "Option 2: Install Homebrew first, then GitHub CLI"
echo "-------------------------------------------------"
echo "If you don't have Homebrew, run these commands:"
echo "  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo "  brew install gh"
echo ""
echo "Option 3: Manual download"
echo "-------------------------"
echo "1. Visit: https://github.com/cli/cli/releases/latest"
echo "2. Download the appropriate version for your Mac (Intel or Apple Silicon)"
echo "3. Extract the archive and move 'gh' to /usr/local/bin/"
echo ""
echo "After installation, authenticate with:"
echo "  gh auth login"
echo ""
echo "Then come back to push your repository!"