#!/bin/bash

echo "GitHub Repository Setup"
echo "====================="
echo ""
echo "Since GitHub CLI installation is blocked, here are your options:"
echo ""
echo "Option 1: Manual GitHub Setup (Easiest)"
echo "--------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Create a new repository named: sb1-bt4uafxr-2222"
echo "3. Make it public, don't initialize with README"
echo "4. After creating, run these commands in this directory:"
echo ""
echo "   git remote add origin https://github.com/JayG2024/sb1-bt4uafxr-2222.git"
echo "   git push -u origin main"
echo ""
echo "Option 2: Install GitHub CLI in Terminal"
echo "---------------------------------------"
echo "Open a regular Terminal (outside of Claude Code) and run:"
echo "   brew install gh"
echo "   gh auth login"
echo ""
echo "Then come back here and run:"
echo "   gh repo create sb1-bt4uafxr-2222 --public --source=. --push"
echo ""
echo "Current git status:"
git status --short